<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cancel' => 'Отмена',
    'Change status' => 'Изменить статус',
    'Close' => 'Закрыть',
    'Create delivery method' => 'Создать способ доставки',
    'Create status' => 'Создать статус',
    'Customer name' => 'Имя Клиента',
    'Delete' => 'Удалить',
    'Delivery method' => 'Способ доставки',
    'Delivery methods' => 'Способы доставки',
    'ID' => 'Идентификатор',
    'Id' => 'Идентификатор',
    'Logo' => 'Лого',
    'Manage' => 'Управление',
    'Order #' => 'Заказ №',
    'Order Statuses' => 'Статусы заказа',
    'Order details' => 'Детали заказа',
    'Order list' => 'Список заказа',
    'Order status' => 'Статус заказа',
    'Patronymic' => 'Отчество',
    'Phone number' => 'Номер телефона',
    'Product list' => 'Список товаров',
    'Save' => 'Сохранить',
    'Show address fields' => 'Показать поля адреса',
    'Show nothing' => 'Ничего не показывать',
    'Show post office field' => 'Показывать поле почтового отделения',
    'Status and details' => 'Статус и детали',
    'Surname' => 'Фамилия',
    'Title' => 'Наименование',
];
