<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Cancel' => 'Скасувати',
    'Change status' => 'Змінити статус',
    'Close' => 'Закрити',
    'Create delivery method' => 'Створити спосіб доставки',
    'Create status' => 'Створити статус',
    'Customer name' => 'Ім\'я клієнта',
    'Delete' => 'Видалити',
    'Delivery method' => 'Спосіб доставки',
    'Delivery methods' => 'Способи доставки',
    'ID' => 'Ідентифікатор',
    'Id' => 'Ідентифікатор',
    'Logo' => 'Лого',
    'Manage' => 'Управління',
    'Order #' => 'Замовлення №',
    'Order Statuses' => 'Статуси замовлення',
    'Order details' => 'Деталі замовлення',
    'Order list' => 'Список замовлення',
    'Order status' => 'Статус замовлення',
    'Patronymic' => 'По батькові',
    'Phone number' => 'Номер телефону',
    'Product list' => 'Список товарів',
    'Save' => 'Зберегти',
    'Show address fields' => 'Показати поля адреси',
    'Show nothing' => 'Нічого не показувати',
    'Show post office field' => 'Показувати поле поштового відділення',
    'Status and details' => 'Статус і деталі',
    'Surname' => 'Прізвище',
    'Title' => 'Найменування',
];
